[id='wb-employee-rostering-data-model-proc']
= Create the data model for the employee rostering project

Use this section to create the data objects required to run the employee rostering sample project in {CENTRAL}.

.Prerequisite 
You have completed the project set up described in <<wb-employee-rostering-example-setup-proc>>.

.Procedure 
//TODO: SolverTest data object.
. With your new project, either click *Data Object* in the project perspective, or click *Create New Asset* -> *Data Object* to create a new data object.
. In the *Create new Data Object* window, create a new data object with the following properties:
+
* *Data Object*: `Timeslot`
* *Package*: `employeerostering.employeerostering`
+
Click *Ok* to create the data object.
. Remove the default field.
. Add the following fields with the given type:
+
DayOffRequest::
* `date`: `LocalDate`
* `employee`: `employeerostering.employeerostering.Employee`
+
ShiftAssignment::
* `employee`: `employeerostering.employeerostering.Employee`
* `shift`: `employeerostering.employeerostering.Shift`


For more information about creating data objects, see {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_].
