[id='case-management-dynamic-user-task-API-proc']
= Creating a dynamic user task using the REST API

You can create a dynamic user task during case run time using the REST API. To create a dynamic user task, the following information must be given:

<<<<<<< HEAD
* Task name
* Task description (optional, but recommended)
* Actors or groups (or both)
* Input data
=======
* task name
* task description (optional, but recommended)
* actors
* groups
* input data
>>>>>>> BXMSDOC-2577: dynamic tasks and process with the API

Use the following procedure to create a dynamic user task for the IT Orders sample project available in {CENTRAL} using the Swagger REST API tool. The same endpoint can be used for REST API without Swagger.

.Prerequisite 
You are logged in to {CENTRAL} and an IT Orders case instance has been started using the Showcase application. For more information about using Showcase, see 
ifeval::["{context}" == "case-management-design"]
xref:case-management-showcase-application-con-case-management-design[Case management Showcase application].
endif::[]


.Procedure 

. In a web browser, open the following URL:
+
`http://localhost:8080/kie-server/docs`.
. Open the list of available endpoints under *Case instances :: Case Management*.
. Click click the following `POST` method endpoint to open the details: 
+
`/server/containers/{id}/cases/instances/{caseId}/tasks`
+
. Click *Try it out* to complete the following parameters:
+
<<<<<<< HEAD
.Parameters
[cols="40%,60%",options="header"]
|===
|Name| Description
|`id` | `itorders`
|`caseId` | `IT-0000000001`
|===
+
=======
id:: `itorders`
caseId:: `IT-0000000001`
>>>>>>> BXMSDOC-2577: dynamic tasks and process with the API
body::
+
[source]
----
{
 "name" : "RequestManagerApproval",
 "data" : {
   "reason" : "Fixed hardware spec",
   "caseFile_hwSpec" : "#{caseFile_hwSpec}"
  }, 
 "description" : "Ask for manager approval again",
 "actors" : "manager",
 "groups" : "" 
}
----
. In the Swagger application, click *Execute* to create the dynamic task.

This procedure creates a new user task associated with case `IT-000000001`. The task is assigned to the person assigned to the `manager` case role. This task has two input variables:

* `reason`
* `caseFile_hwSpec`: defined as an expression to allow run time capturing of process or case data.

Depending on the task, a form might be defined to provide a user-friendly UI for the task, which can be looked up by task name. In the IT Orders case, the `RequestManagerApproval` task includes the form `RequestManagerApproval-taskform.form` in its KJAR. 

<<<<<<< HEAD
After it is created, the task appears in the assignee's *Task Inbox* in {CENTRAL}.
=======
Once the task has been created, the task appears in the assignee`s *Task Inbox* in {CENTRAL}.

>>>>>>> BXMSDOC-2577: dynamic tasks and process with the API
