[id='case-management-milestones-con-{context}']
= Milestones

Milestones are a special service task that can be configured in the case definition designer by adding the `Milestone` node to the case design palette. When creating a new case definition, a `Milestone` configured as `Adhoc autostart` is included on the design palette by default. 

Case management milestones usually occurs at the end of a stage, but can also be the result of achieving other milestones. Milestones react to case file data when data is added to a case. A milestone represents a single point of achievement within the case instance, and can be used to flag certain progress, which can be valuable for KPI tracking or identifying the tasks that are still to be completed.


There are two ways to achieve a milestone:

* It can be triggered using a signal or API call.
* It can meet the completion condition.

Milestones can have three states:

* Active - the condition has been defined on the milestone but it has not been met. 
* Completed - the milestone condition has been met and the milestone has been achieved and the case can proceed to the next task.
* Terminated - the milestone is no longer a part of the case process and is no longer required.
 
While a milestone is available or completed it can be triggered manually using a signal or can be automatically started (by configuring `Adhoc autostart`) when a case instance starts. Milestones can be triggered as many times as required.
 


